# Generated by Django 6.0.6 on 2026-06-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banklist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "bank_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "statement_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("drive_link", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="banklist.bank"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="banklist.company",
                    ),
                ),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ["-created_at"],
                "unique_together": {("company", "account_number", "bank")},
            },
        ),
    ]
